# Site settings
title: Caleydo
email: contact@caleydo.org
description: "Caleydo: Visualization for BioMedicine."
baseurl: ""
url: "http://caleydo.org"
twitter_username: caleydo_org
github_username:  caleydo
youtube_username: caleydotugraz
facebook_page: Caleydo/110550618994500
license_url: https://raw.githubusercontent.com/Caleydo/caleydo/develop/LICENSE
safe: false
lsi: false
google_analytics: "'UA-45998043-1'"
use_analytics: true

paper_content_url: http://data.caleydo.org/papers/
data_url: http://data.caleydo.org/

gems:
  - jekyll-redirect-from
  - kramdown # In particular, MD rendering within the repo list

# Build settings

permalink: pretty
sass:
  sass_dir: _sass
exclude: ["README.md", "Rakefile", "changelog.md", ".idea/", "Gemfile", "Gemfile.lock", "rvm.env"]

collections:
  institutions:
    output: false
  welcome:
    output: true
  tutorials:
    output: true
  developers:
    output: true
  reference:
    output: true
